### ISSUE TITLE
Milestone 2 feedback

### ISSUE THREAD

**Issue by lmguzman** [UBC-MDS/pyfer#26]
Good job on this milestone! The package installed easily and I was able to run all your functions. 

Here are is some feedback for your next milestone:

- I copied and pasted your usage exactly as you put it in your documentation, but I couldn't run the functions as is. I had to write `pyfer.specify(mpg,response="acceleration")`. You should change the documentation so that it can be copied and pasted. 

- I ran generate with n_samples = -5, it didn’t give me anything. Shouldn't this give me an error?

- If I put in a data frame with multiple columns in the function generate, does every column get resampled? And do the rows remained tied?. 

- In your input it says I could give a data frame with one response and multiple explanatory to the unction generate, which I did, and I obtained a resampled data frame. Then I tried to input this resampled data frame to the calculate function and I had an error. If calculate can’t deal with multiple columns, then it shouldn’t be accepted as an input for generate.

**Comment by GabrielBogo** [comment]
Hi, Melissa. All the feedbacks above were addressed in Pull Request #35. Thank you for the suggestions.
