### ISSUE TITLE
Proposal feedback 

### ISSUE THREAD

**Issue by lmguzman** [UBC-MDS/pyfer#5]
Great job on your proposal!

The description of the package is very clear and easy to understand. 

- I think you need more details on the function generate such as the size of the data frame you expect (especially since you are this explicit on the subsequent function description).

- If the infer package is supposed to use within the tidy verse world, I'm wondering why you need a specify function, do you have an equivalent in python? and will you just use a wrapper for this? You can be more specific on what is already available and what you are going to wrap around for this function.

**Comment by GabrielBogo** [comment]
@lmguzman Thank you for your feedback. See our position below:

- We rephrased the description of `generate`, focussing on the number of columns. For the number of rows, we simply said that all resamples will be stacked vertically (it may be easier than putting a formula there)
- We went over the documentation for `specify` in the `infer` package, and it is indeed a very simple function. The main idea is to factor out the variable selection from the other functions, maybe just for readability purposes. Therefore, it applies for both R and Python. But you're right, this function is just a wrapper around a subsetting of dataframe columns plus some data validation. We decided to keep it trusting that the infer team had a very good reason for that as well.
